---

- name: General Config on Physical Interfaces
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Add description to interfaces
      nxos_interfaces:
        config:
          - name: Ethernet1/10
            description: 'L3 interface by Ansible Tower'
            enabled: True
          - name: Ethernet1/11
            description: 'L2 interface by Ansible Tower'
            enabled: True
        state: merged

- name: VLAN Provision
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Create a vlan on device
      nxos_vlans:
        config:
          - vlan_id: "{{ vlan }}"
            name: test-vlan
            state: active
        state: replaced

- name:  L2 and L3 config on interfaces
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Configure L3 Interfaces
      nxos_l3_interfaces:
        config:
          - name: Ethernet1/10
            ipv4:
              - address: 192.168.1.1/24
                tag: 5
              - address: 10.1.1.1/24
                secondary: True
                tag: 10
            ipv6:
              - address: fd5d:12c9:2201:2::1/64
                tag: 6
        state: merged

    - name: Configure L2 Interfaces
      nxos_l2_interfaces:
        config:
          - name: interface=Ethernet1/11
            trunk:
            trunk_vlans: "{{ vlan }}"
        state: merged
   
