---

- name: General Config on Physical Interfaces
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Add description to interfaces
      nxos_interfaces:
        config:
          - name: Ethernet1/10
            description: 'Conf by Ansible'
            mode: layer2
            enabled: True
          - name: Ethernet1/11
            description: 'Conf by Ansible'
            mode: layer3
            enabled: True
        state: replaced

- name: VLAN Provision
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Create a vlan on device
      nxos_vlans:
        config:
          - vlan_id: '299'
            name: 'ansible_tower_vlan'
            state: active
        state: replaced

- name:  L2 and L3 config on interfaces
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Configure L2 Interfaces
      nxos_l2_interfaces:
        config:
          - name: Ethernet1/10
            trunk:
              native_vlan: 1
              allowed_vlans: 299
        state: merged
        
    - name: Configure L3 Interfaces
      nxos_l3_interfaces:
        config:
          - name: Ethernet1/11
            ipv4: 
              - address: 192.168.222.1/24
        state: merged
 
