---
- name: setup control node timestamp
  hosts: ansible
  gather_facts: no
  become: yes
  tasks:

    - name: create /backup directory on control node
      file:
        path: /backup
        state: directory

- name: retrieve router configurations
  hosts: all
  gather_facts: no

  tasks:
    - name: backup configuration
      include_role:
        name: backup
      when: ansible_network_os is defined

    - name: SAVE CONFIGURATION LOCALLY
      vars:
        ansible_connection: ssh
      copy:
        src: "{{config_output.stdout}}"
        dest: "/backup/{{inventory_hostname}}"
      delegate_to: ansible
      when: config_output is defined
      become: yes


- name: backup router configurations
  hosts: ansible
  gather_facts: no
  tasks:
    - name: find backups
      find:
        paths: /backup
        file_type: directory
      register: backups
      run_once: true
      become: yes
