# This task will backup the configuration
- name: BACKUP THE CONFIG
  nxos_config:
    backup: yes
  register: config_output

# This task removes the Current configuration... from the top of NXOS routers show run
- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{config_output.backup_path}}"
    line: "Building configuration..."
    state: absent
